# Generated by Django 3.2 on 2022-06-30 02:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movieRecommend', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='movie',
            fields=[
                ('movieid', models.AutoField(primary_key=True, serialize=False)),
                ('moviename', models.CharField(max_length=100)),
                ('rating', models.FloatField()),
                ('poster', models.CharField(max_length=200)),
                ('languages', models.CharField(max_length=20)),
                ('year', models.IntegerField()),
                ('summary', models.TextField()),
                ('duration', models.CharField(max_length=200)),
                ('rating_people', models.IntegerField()),
                ('rating_average', models.FloatField()),
                ('percentage5', models.FloatField()),
                ('percentage4', models.FloatField()),
                ('percentage3', models.FloatField()),
                ('percentage2', models.FloatField()),
                ('percentage1', models.FloatField()),
            ],
        ),
        migrations.DeleteModel(
            name='User',
        ),
    ]
