# Generated by Django 3.2 on 2022-06-30 02:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('movieRecommend', '0002_auto_20220630_1000'),
    ]

    operations = [
        migrations.CreateModel(
            name='user_rating',
            fields=[
                ('userid', models.AutoField(primary_key=True, serialize=False)),
                ('rating', models.FloatField()),
                ('timestamp', models.CharField(max_length=10)),
                ('movieid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='movieRecommend.movie')),
            ],
        ),
    ]
