# Generated by Django 3.2 on 2022-06-30 02:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movieRecommend', '0003_user_rating'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='movieid',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
