# Generated by Django 3.2 on 2022-06-30 02:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movieRecommend', '0004_alter_movie_movieid'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='movie',
            name='rating_average',
        ),
    ]
