# Generated by Django 3.2 on 2022-06-30 03:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('movieRecommend', '0006_genre'),
    ]

    operations = [
        migrations.CreateModel(
            name='directors',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('directors', models.CharField(max_length=20)),
                ('movieid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='movieRecommend.movie')),
            ],
        ),
        migrations.CreateModel(
            name='comments',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comments_name', models.CharField(max_length=50)),
                ('comments_txt', models.TextField()),
                ('rating', models.FloatField()),
                ('movieid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='movieRecommend.movie')),
            ],
        ),
        migrations.CreateModel(
            name='casts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('casts', models.CharField(max_length=200)),
                ('movieid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='movieRecommend.movie')),
            ],
        ),
    ]
