# Generated by Django 3.2 on 2022-06-30 03:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movieRecommend', '0007_casts_comments_directors'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='languages',
            field=models.CharField(max_length=100),
        ),
    ]
