# Generated by Django 3.2 on 2022-06-30 07:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movieRecommend', '0009_alter_movie_languages'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='movieid',
            field=models.IntegerField(primary_key=True, serialize=False, unique=True),
        ),
    ]
