# Generated by Django 3.2 on 2022-06-30 08:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movieRecommend', '0010_alter_movie_movieid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='directors',
            name='directors',
            field=models.CharField(max_length=200),
        ),
    ]
